[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "ratelimiter"
version = "1.2.0"
description = "A rate-limiting library"
authors = ["Frazer McLean <frazer@frazermclean.co.uk>"]
